export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  ADMIN_DASHBOARD: "/admin/dashboard",
  DOCTOR_DASHBOARD: "/doctor/dashboard",
  DOCTOR_SCHEDULE: "/doctor/schedule",
  DOCTOR_CALENDAR: "/doctor/calendar",
  DOCTOR_TODAY: "/doctor/today",
  DOCTOR_PATIENTS: "/doctor/patients",
  DOCTOR_PATIENT_DETAIL: "/doctor/patients/:patientId",
  DOCTOR_AI_CONVERSATIONS: "/doctor/ai-conversations",
  DOCTOR_AVAILABILITY: "/doctor/availability",
  DOCTOR_NOTIFICATIONS: "/doctor/notifications",
  DOCTOR_PROFILE: "/doctor/profile",
  DOCTOR_SETTINGS: "/doctor/settings",
  SECRETARY_DASHBOARD: "/secretary/dashboard",
  PATIENT_DASHBOARD: "/patient/dashboard",
} as const;
